site_name: Odyssey Documentation

repo_url: https://github.com/johnhalz/Odyssey
repo_name: johnhalz/Odyssey

copyright: Copyright &copy; 2024 John Halazonetis

theme:
  name: material
  logo: img/logo_white.svg
  favicon: img/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/johnhalz/Odyssey

nav:
  - Introduction: "index.md"
  - Database:
      - Database Schema: "database/schema.md"
  - API:
      - API Usage: "api_docs/usage.md"
  - Development Setup Guide:
      - Database Setup: "development_guide/database_setup.md"
      - Python Environment Setup: "development_guide/python_setup.md"
      - Making Migrations & Adding Seed Data: "development_guide/migrations.md"
      - Running Server & Creating an Admin Account: "development_guide/running_first_time.md"
