# Generated by Django 5.0 on 2023-12-30 18:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('conversion_to_base', models.CharField(default='x', max_length=80)),
                ('abbreviation', models.CharField(max_length=10)),
                ('base_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyssey_production.unit')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odyssey_production.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField()),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='odyssey_production.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Decimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal', models.FloatField()),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='odyssey_production.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Array',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='odyssey_production.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
