# Generated by Django 5.0 on 2023-12-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey_production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='name',
        ),
    ]
