# Generated by Django 5.0 on 2023-12-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey_production', '0002_remove_value_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='base_unit_id',
            new_name='base_unit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='type_id',
            new_name='type',
        ),
    ]
