# Generated by Django 5.0 on 2023-12-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey_production', '0003_rename_base_unit_id_unit_base_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='odyssey_production.unit'),
        ),
    ]
