# Generated by Django 5.0 on 2023-12-31 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey_production', '0004_alter_unit_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odyssey_production.unit'),
        ),
    ]
