# Generated by Django 5.0.4 on 2024-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey_production', '0005_alter_unit_base_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='conversion_to_base',
        ),
        migrations.AddField(
            model_name='unit',
            name='denominator',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='multiplicand',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='x_offset',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='y_offset',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19, null=True),
        ),
    ]
