# Generated by Django 5.0.4 on 2024-04-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey_production', '0006_remove_unit_conversion_to_base_unit_denominator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='plural_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='space_after_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='denominator',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='unit',
            name='multiplicand',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='unit',
            name='x_offset',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='unit',
            name='y_offset',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
