# Generated by Django 5.0.4 on 2024-04-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionstepmodel_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstep',
            options={'verbose_name': 'Production Step', 'verbose_name_plural': 'Production Steps'},
        ),
        migrations.AlterModelOptions(
            name='productionstepmodel',
            options={'verbose_name': 'Production Step Model', 'verbose_name_plural': 'Production Step Models'},
        ),
    ]
