# Generated by Django 5.0.4 on 2024-04-20 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_productionstep_production_step_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionstep',
            old_name='end_timestamp',
            new_name='end_ts',
        ),
        migrations.RenameField(
            model_name='productionstep',
            old_name='start_timestamp',
            new_name='start_ts',
        ),
        migrations.AddField(
            model_name='configuration',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productionstepmodel',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
