# Generated by Django 5.0.4 on 2024-04-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_rename_end_timestamp_productionstep_end_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='production.configuration'),
        ),
    ]
