# Generated by Django 5.0.4 on 2024-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_configuration_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstepmodel',
            name='step_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
