# Generated by Django 5.0.4 on 2024-04-20 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0005_alter_equipment_number'),
        ('production', '0003_alter_productionstep_options_and_more'),
        ('values_and_units', '0007_alter_array_unit_alter_decimal_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commencement_date', models.DateField(blank=True, default=None, null=True)),
                ('expiration_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Specification Group',
                'verbose_name_plural': 'Specification Groups',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testing.measurement')),
                ('production_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='production.productionstep')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='values_and_units.value')),
            ],
        ),
        migrations.CreateModel(
            name='NonCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('decision', models.TextField(blank=True, default=None, null=True)),
                ('create_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_non_compliances', to=settings.AUTH_USER_MODEL)),
                ('signer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='signed_non_compliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non-Compliance',
                'verbose_name_plural': 'Non-Compliances',
            },
        ),
        migrations.CreateModel(
            name='NonComplianceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('create_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_compliance_comments', to=settings.AUTH_USER_MODEL)),
                ('non_compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testing.noncompliance')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='testing.noncompliancecomment')),
            ],
            options={
                'verbose_name': 'Non-Compliance Comment',
                'verbose_name_plural': 'Non-Compliance Comments',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('processor_name', models.CharField(max_length=255)),
                ('measurements', models.ManyToManyField(blank=True, related_name='results', to='testing.measurement')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testing.result')),
                ('processor_version', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='values_and_units.version')),
                ('value', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='values_and_units.value')),
            ],
        ),
        migrations.AddField(
            model_name='noncompliance',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_compliances', to='testing.result'),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('severity', models.CharField(max_length=100)),
                ('applicable_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_specifications', to='values_and_units.range')),
                ('hardware_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='hardware.hardwaremodel')),
                ('production_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='production.productionstep')),
                ('valid_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validating_specifications', to='values_and_units.range')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='values_and_units.version')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='testing.specificationgroup')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='results', to='testing.specification'),
        ),
    ]
