# Generated by Django 5.0.4 on 2024-04-20 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='specificationgroup',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
