# Generated by Django 5.0.4 on 2024-04-20 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_remove_result_specifications_result_specification'),
        ('values_and_units', '0008_unit_create_ts_value_create_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.FilePathField(path='.', recursive=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='values_and_units.version')),
            ],
        ),
    ]
