# Generated by Django 5.0.4 on 2024-04-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_hardware_create_ts'),
        ('production', '0006_configuration_parent'),
        ('testing', '0005_remove_result_processor_name_and_more'),
        ('values_and_units', '0008_unit_create_ts_value_create_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='production_step',
        ),
        migrations.AddField(
            model_name='noncompliance',
            name='close_ts',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='production_step_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='specifications', to='production.productionstepmodel'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='applicable_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scoped_specifications', to='values_and_units.range'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='hardware_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='specifications', to='hardware.hardwaremodel'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='valid_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='validating_specifications', to='values_and_units.range'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='specifications', to='values_and_units.version'),
        ),
    ]
