# Generated by Django 5.0.4 on 2024-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_processor_production_step_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationgroup',
            name='commencement_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='specificationgroup',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
