# Generated by Django 5.0.4 on 2024-04-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_hardwaremodel_version_delete_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hardware.equipment'),
        ),
        migrations.AlterField(
            model_name='hardwaremodel',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hardware.hardwaremodel'),
        ),
    ]
