# Generated by Django 5.0.4 on 2024-04-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_equipment_create_ts_hardwaremodel_create_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='set',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
