# Generated by Django 5.0.4 on 2024-04-20 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_alter_hardware_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
