# Generated by Django 5.0.4 on 2024-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='serial_number',
            field=models.CharField(max_length=255),
        ),
    ]
