# Generated by Django 5.0.4 on 2024-04-16 20:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Unit Types',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('plural_name', models.CharField(blank=True, max_length=30, null=True)),
                ('space_after_value', models.BooleanField(default=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('x_offset', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('y_offset', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('multiplicand', models.DecimalField(decimal_places=10, default=1, max_digits=19)),
                ('denominator', models.DecimalField(decimal_places=10, default=1, max_digits=19)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField()),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Decimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal', models.FloatField()),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Array',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
