# Generated by Django 5.0.4 on 2024-04-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values_and_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('major', models.IntegerField(default=1)),
                ('minor', models.IntegerField(default=0)),
                ('patch', models.IntegerField(default=0)),
            ],
        ),
    ]
