# Generated by Django 5.0.4 on 2024-04-16 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('values_and_units', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit'),
        ),
        migrations.AlterField(
            model_name='value',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('integer', 'decimal', 'array', 'string')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lower', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lower_ranges', to='values_and_units.value')),
                ('upper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='upper_ranges', to='values_and_units.value')),
            ],
        ),
    ]
