# Generated by Django 5.0.4 on 2024-04-16 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values_and_units', '0003_value_unit_alter_value_content_type_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='array',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='decimal',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='integer',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='range',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='string',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='value',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='version',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
