# Generated by Django 5.0.4 on 2024-04-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('values_and_units', '0005_remove_value_create_ts_remove_value_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('integer', 'decimal', 'array', 'string')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
