# Generated by Django 5.0.4 on 2024-04-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values_and_units', '0006_alter_value_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit'),
        ),
        migrations.AlterField(
            model_name='decimal',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit'),
        ),
        migrations.AlterField(
            model_name='integer',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='values_and_units.unit'),
        ),
    ]
