# Generated by Django 5.0.4 on 2024-04-20 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values_and_units', '0007_alter_array_unit_alter_decimal_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='value',
            name='create_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
