# Generated by Django 5.0.4 on 2024-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values_and_units', '0008_unit_create_ts_value_create_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='string',
            name='string',
            field=models.CharField(max_length=255),
        ),
    ]
